#ifndef FBC_MESSY_TEST_AGGREGATE_INITIALIZATION_HPP_
#define FBC_MESSY_TEST_AGGREGATE_INITIALIZATION_HPP_

int test_designated_initializers();

#endif // FBC_MESSY_TEST_AGGREGATE_INITIALIZATION_HPP_
